[package]
name = "csenums"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.65"
proc-macro2 = "1.0.83"
quote = "1.0.36"
darling = "0.20.9"
proc-macro-error = "1.0.4"